/// Collects every `commands::name` registered in `generate_handler![...]` so
/// the IPC access-control list always matches the real handler list.
fn registered_app_commands() -> Vec<String> {
    let source = std::fs::read_to_string("src/lib.rs").expect("failed to read src/lib.rs");
    let start = source
        .find("generate_handler![")
        .expect("generate_handler! not found in src/lib.rs");
    let body = &source[start..];
    let body = &body[..body.find(']').expect("unterminated generate_handler!")];
    let mut commands: Vec<String> = body
        .split(|c: char| c == ',' || c.is_whitespace())
        .filter_map(|token| token.strip_prefix("commands::"))
        .map(str::to_string)
        .collect();
    commands.sort();
    commands.dedup();
    assert!(
        !commands.is_empty(),
        "no commands found in generate_handler!"
    );
    commands
}

/// Writes the permission set that grants the app's own UI every command.
/// Remote pages shown in the in-app browser get a separate, minimal
/// capability (see capabilities/browser-bridge.json).
fn write_app_command_set(commands: &[String]) {
    let mut toml = String::from(
        "# Generated by build.rs from generate_handler! in src/lib.rs. Do not edit.\n\n\
         [[set]]\n\
         identifier = \"app-commands\"\n\
         description = \"Every command the app's own UI may invoke.\"\n\
         permissions = [\n",
    );
    for command in commands {
        toml.push_str(&format!("  \"allow-{}\",\n", command.replace('_', "-")));
    }
    toml.push_str("]\n");

    let path = std::path::Path::new("permissions/app-commands.toml");
    std::fs::create_dir_all("permissions").expect("failed to create permissions dir");
    if std::fs::read_to_string(path).ok().as_deref() != Some(toml.as_str()) {
        std::fs::write(path, toml).expect("failed to write permissions/app-commands.toml");
    }
}

fn main() {
    println!("cargo:rerun-if-changed=src/lib.rs");
    let commands = registered_app_commands();
    write_app_command_set(&commands);
    let commands: &'static [&'static str] = Box::leak(
        commands
            .into_iter()
            .map(|command| &*Box::leak(command.into_boxed_str()))
            .collect::<Vec<_>>()
            .into_boxed_slice(),
    );

    // Declaring an app manifest makes Tauri enforce capabilities for app
    // commands too. Without it any page loaded in the in-app browser could
    // call every command (file writes, terminal input, ...).
    //
    // Use tauri-build WITHOUT its default application manifest. We embed the
    // Common-Controls v6 manifest ourselves below so that it reaches every
    // target (bins, cdylib, and — critically — `cargo test` unit-test binaries).
    // tauri-build's default path only embeds the manifest into `bin` targets,
    // which leaves `cargo test` binaries without it; `tao` then imports
    // `TaskDialogIndirect` from comctl32.dll, which only exists in the v6
    // common-controls assembly, and the test binary dies at load with
    // 0xc0000139 (STATUS_ENTRYPOINT_NOT_FOUND).
    if let Err(error) = tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(commands))
            .windows_attributes(tauri_build::WindowsAttributes::new_without_app_manifest()),
    ) {
        let error = format!("{error:#}");
        println!("{error}");
        std::process::exit(1);
    }

    #[cfg(target_os = "windows")]
    {
        const APP_MANIFEST: &str = r#"<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
        type="win32"
        name="Microsoft.Windows.Common-Controls"
        version="6.0.0.0"
        processorArchitecture="*"
        publicKeyToken="6595b64144ccf1df"
        language="*"
      />
    </dependentAssembly>
  </dependency>
</assembly>"#;

        let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is not set");
        let rc_path = std::path::Path::new(&out_dir).join("app-manifest.rc");

        let mut rc = String::from("#pragma code_page(65001)\n1 24\n{\n");
        for line in APP_MANIFEST.lines() {
            let escaped = line.replace('"', "\"\"");
            rc.push_str(&format!("\" {} \"\n", escaped.trim()));
        }
        rc.push_str("}\n");

        std::fs::write(&rc_path, rc).expect("failed to write app manifest rc");
        embed_resource::compile_for_everything(rc_path.to_str().unwrap(), embed_resource::NONE)
            .manifest_required()
            .expect("failed to embed app manifest");
    }
}
