import React from 'react';
import {
  Article,
  Bank,
  BookOpen,
  Books,
  Calculator,
  CalendarCheck,
  ChartBar,
  ChartLineUp,
  Cpu,
  Flask,
  Gear,
  Globe,
  GraduationCap,
  HandHeart,
  Handshake,
  Kanban,
  Lightbulb,
  MagnifyingGlass,
  Notebook,
  PenNib,
  Rocket,
  Scales,
  ShieldCheck,
  Siren,
  Sparkle,
  SquaresFour,
  TestTube,
  TrendUp,
  UsersThree,
  type Icon,
} from '@phosphor-icons/react';

const ICONS: Record<string, Icon> = {
  Article,
  Bank,
  BookOpen,
  Books,
  Calculator,
  CalendarCheck,
  ChartBar,
  ChartLineUp,
  Cpu,
  Flask,
  Gear,
  Globe,
  GraduationCap,
  HandHeart,
  Handshake,
  Kanban,
  Lightbulb,
  MagnifyingGlass,
  Notebook,
  PenNib,
  Rocket,
  Scales,
  ShieldCheck,
  Siren,
  Sparkle,
  SquaresFour,
  TestTube,
  TrendUp,
  UsersThree,
};

export const ReportIcon: React.FC<{ name: string; size?: number }> = ({ name, size = 18 }) => {
  const Component = ICONS[name] ?? Sparkle;
  return <Component size={size} weight="light" aria-hidden="true" />;
};
