export const aiAgentsContent = `# AI Agents

YzPzCode detects, installs, authenticates, and launches AI coding agents into terminal panes. Each agent is a CLI tool that runs in your workspace directory.

## Supported Agents

| Agent | CLI Command | What it does |
|-------|-------------|-------------|
| **Claude Code** | \`claude\` | Anthropic's advanced AI coding assistant |
| **Codex CLI** | \`codex\` | OpenAI's code generation and development CLI |
| **Gemini CLI** | \`gemini\` | Google's Gemini assistant for terminal-based development |
| **OpenCode** | \`opencode\` | Open-source AI command-line coding assistant |
| **Cursor CLI** | \`agent\` | Cursor's AI-enhanced development agent |
| **Kilo CLI** | \`kilo\` | Agentic coding CLI with TUI and autonomous mode |
| **Hermes Agent** | \`hermes\` | Autonomous agent with tool use and multi-modal capabilities |
| **Pi Agent** | \`pi\` | Minimal terminal coding harness with extensions and skills |
| **Command Code** | \`cmd\` / \`cmdc\` | Agentic coding CLI that learns your taste and applies it to every session |
| **Cline CLI** | \`cline\` | Agentic coding CLI with interactive TUI and headless automation |
| **Grok CLI** | \`grok\` | xAI's agentic coding assistant |

## Installing and Signing In

1. Install the CLI for the agent you want. Each missing agent in the Agent Fleet shows its install command, or see **Settings → CLI tools**
2. Sign in from any terminal: type the tool's name and use its login or authenticate option
3. Click the refresh button in the Agent Fleet to re-detect install and auth status

> **Tip:** You only need to sign in once per tool. YzPzCode checks each agent's credentials and shows an auth badge next to it.

## The YzPz Agent Harness

Alongside external CLIs, YzPzCode ships its own agent harness. It runs as a local Node sidecar, so it needs Node.js installed. Configure it under **Settings → YzPz Agent**.

### Session Modes

| Mode | Behavior |
|------|----------|
| **Ask** | Read-only. Answers questions, reads and searches files, never edits or runs commands |
| **Act** (default) | Full access. Can modify files and execute commands |
| **Plan** | Read-only planning for complex work before acting |
| **Orchestrator** | Coordinates work across sessions |

The mode is enforced: in Ask or Plan mode, file edits and command execution are blocked by a tool guard, so you never have to worry about accidental changes.

### Fast Mode and Token Budget

- **Fast mode**: A per-session toggle that directs the agent to complete the request as fast as possible. Turn it off to let the agent work normally again
- **Token limit**: Set a budget when starting a session (leave it at zero for unlimited). The harness stops the session when the budget is reached, and the usage meter in the agent pane shows live usage against the limit

### Queued Prompts

If an agent is already working and you send another message, it is queued instead of interrupting the running task.

- Queued prompts appear in an **"Up next"** strip above the input box, numbered and in order
- Remove a single prompt with the **X** next to it, or use **Clear all**
- Pressing **Stop** interrupts the running task and clears its queued prompts
- The queue survives a pane refresh

## Images in Agent Chat

- Attach images with the paperclip button or paste them directly into the composer
- Attachments are normalized automatically into a small, provider-neutral JPEG, so oversized or unusual formats do not break the request
- If the selected model does not support vision, you will see a notice asking you to attach a document or choose a vision model instead
- Images generated by the agent appear in the transcript as **Generated image** cards

## Live Model Catalog

The agent harness periodically syncs the provider and model catalog from models.dev. When new models are published, they appear in the model pickers without restarting the app. You can also refresh manually with the **Refresh model catalog** button under **Settings → YzPz Agent**.

## Quick Prompts

Quick prompts are preset, clickable prompts shown as a row of chips under the agent input when it is idle. Clicking a chip appends its text to the message box so you can review or edit it before sending.

Configure your own presets under **Settings → Quick prompts**, where you can add, edit, remove, and drag-to-reorder prompts in two groups (Enhance and Adjust / Edit), or reset to the defaults. The same presets also appear in the terminal quick prompt strip and the element inspector panel.
`;
