// Word import: .docx → HTML (mammoth) → the editor's own node markup.
// Images are copied into the report's assets folder; footnotes, captions and
// quotes are mapped onto the writing nodes so they export again natively.

import { invoke } from '@tauri-apps/api/core';
import { joinPath } from './document';
import { readBytes } from './sources';

const STYLE_MAP = [
  "p[style-name='Title'] => h1.doc-title:fresh",
  "p[style-name='Subtitle'] => p.doc-subtitle:fresh",
  "p[style-name='Caption'] => p.caption:fresh",
  "p[style-name='Quote'] => blockquote > p:fresh",
  "p[style-name='Intense Quote'] => blockquote > p:fresh",
  "p[style-name='Bibliography'] => p.bibliography:fresh",
  "p[style-name='TOC Heading'] => p.toc-heading:fresh",
  "p[style-name^='TOC'] => p.toc-entry:fresh",
  "p[style-name='Heading 5'] => h4:fresh",
  "p[style-name='Heading 6'] => h4:fresh",
  "r[style-name='Strong'] => strong",
  "r[style-name='Emphasis'] => em",
];

export interface ImportedDocx {
  html: string;
  title: string;
  warnings: string[];
}

const extensionFor = (contentType: string): string => {
  const subtype = contentType.split('/')[1] ?? 'png';
  return subtype === 'jpeg' ? 'jpg' : subtype.replace(/[^a-z0-9]/gi, '') || 'png';
};

/** Rewrites mammoth's HTML into the markup the editor's extensions parse. */
export function normalizeImportedHtml(raw: string): { html: string; title: string } {
  const doc = new DOMParser().parseFromString(`<body>${raw}</body>`, 'text/html');
  const body = doc.body;

  // Footnotes: mammoth emits <sup><a href="#footnote-1">[1]</a></sup> plus a trailing list.
  const notes = new Map<string, string>();
  body.querySelectorAll('li[id^="footnote-"], li[id^="endnote-"]').forEach((item) => {
    item.querySelectorAll('a[href^="#footnote-ref"], a[href^="#endnote-ref"]').forEach((back) => back.remove());
    notes.set(item.id, item.textContent?.trim() ?? '');
  });
  body.querySelectorAll('sup > a[href^="#footnote-"], sup > a[href^="#endnote-"]').forEach((anchor) => {
    const id = anchor.getAttribute('href')?.slice(1) ?? '';
    const sup = anchor.parentElement!;
    const replacement = doc.createElement('sup');
    replacement.setAttribute('data-footnote', notes.get(id) ?? '');
    sup.replaceWith(replacement);
  });
  body.querySelectorAll('ol').forEach((list) => {
    if (list.querySelector('li[id^="footnote-"], li[id^="endnote-"]')) list.remove();
  });

  // Table-of-contents paragraphs are regenerated by the editor.
  const tocHeading = body.querySelector('p.toc-heading');
  body.querySelectorAll('p.toc-entry, p.toc-heading').forEach((entry) => entry.remove());
  if (tocHeading) {
    const nav = doc.createElement('nav');
    nav.setAttribute('data-toc', '');
    body.prepend(nav);
  }

  // Captions.
  body.querySelectorAll('p.caption').forEach((caption) => {
    const text = caption.textContent ?? '';
    const isFigure = /^\s*(figure|fig\.)/i.test(text);
    caption.setAttribute('data-caption', isFigure ? 'figure' : 'table');
    caption.removeAttribute('class');
    caption.innerHTML = caption.innerHTML.replace(/^\s*(Table|Figure|Fig\.)\s*[\d.]*\s*[:.–—-]?\s*/i, '');
  });

  // Paragraphs that hold only an image become figures (with the following caption, if any).
  body.querySelectorAll('p').forEach((paragraph) => {
    const images = paragraph.querySelectorAll('img');
    if (images.length !== 1 || (paragraph.textContent ?? '').trim() !== '') return;
    const img = images[0];
    const figure = doc.createElement('figure');
    const next = paragraph.nextElementSibling;
    let caption = img.getAttribute('alt') ?? '';
    if (next?.getAttribute('data-caption') === 'figure') {
      caption = next.textContent?.trim() ?? caption;
      next.remove();
    }
    const newImg = doc.createElement('img');
    newImg.setAttribute('src', img.getAttribute('src') ?? '');
    newImg.setAttribute('alt', caption);
    const figcaption = doc.createElement('figcaption');
    figcaption.textContent = caption;
    figure.append(newImg, figcaption);
    paragraph.replaceWith(figure);
  });

  // The Word title becomes the report title rather than a body heading.
  let title = '';
  const titleHeading = body.querySelector('h1.doc-title');
  if (titleHeading) {
    title = titleHeading.textContent?.trim() ?? '';
    titleHeading.remove();
  }
  body.querySelectorAll('p.doc-subtitle').forEach((entry) => entry.remove());
  if (!title) title = body.querySelector('h1')?.textContent?.trim() ?? '';

  // Bibliography paragraphs keep their text; strip classes the schema ignores.
  body.querySelectorAll('[class]').forEach((element) => element.removeAttribute('class'));
  return { html: body.innerHTML, title };
}

export async function importDocx(path: string, docDir: string): Promise<ImportedDocx> {
  const mammoth = await import('mammoth');
  const bytes = await readBytes(path);
  let imageCount = 0;
  const result = await mammoth.convertToHtml(
    { arrayBuffer: bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer },
    {
      styleMap: STYLE_MAP,
      convertImage: mammoth.images.imgElement(async (image) => {
        imageCount += 1;
        const name = `imported-${imageCount}.${extensionFor(image.contentType)}`;
        const base64 = await image.read('base64');
        await invoke('write_file_bytes', { path: joinPath(docDir, 'assets', name), base64Data: base64 });
        return { src: `assets/${name}` };
      }),
    },
  );
  const { html, title } = normalizeImportedHtml(result.value);
  return { html, title, warnings: result.messages.filter((message) => message.type === 'warning').map((message) => message.message) };
}
