/**
 * Convert file extensions and language names into Monaco language IDs.
 * Monaco uses `typescript` for both `.ts` and `.tsx`, for example.
 */
export const toMonacoLanguage = (language: string | null | undefined): string => {
  const key = language?.replace(/^\./, '').toLowerCase() ?? '';
  const languageIds: Record<string, string> = {
    typescript: 'typescript',
    tsx: 'typescript',
    javascript: 'javascript',
    mjs: 'javascript',
    cjs: 'javascript',
    python: 'python',
    rust: 'rust',
    html: 'html',
    htm: 'html',
    css: 'css',
    scss: 'scss',
    less: 'less',
    sass: 'scss',
    json: 'json',
    jsonc: 'json',
    markdown: 'markdown',
    md: 'markdown',
    mdx: 'markdown',
    java: 'java',
    kotlin: 'kotlin',
    kt: 'kotlin',
    cpp: 'cpp',
    c: 'cpp',
    h: 'cpp',
    cc: 'cpp',
    cxx: 'cpp',
    hpp: 'cpp',
    objectivec: 'objective-c',
    'objective-c': 'objective-c',
    ts: 'typescript',
    js: 'javascript',
    jsx: 'javascript',
    py: 'python',
    rs: 'rust',
    txt: 'plaintext',
    yaml: 'yaml',
    yml: 'yaml',
    xml: 'xml',
    svg: 'xml',
    sql: 'sql',
    sh: 'shell',
    bash: 'shell',
    zsh: 'shell',
    fish: 'shell',
    go: 'go',
    php: 'php',
    rb: 'ruby',
    ruby: 'ruby',
    cs: 'csharp',
    csharp: 'csharp',
    dart: 'dart',
    swift: 'swift',
    scala: 'scala',
    lua: 'lua',
    r: 'r',
    perl: 'perl',
    ps1: 'powershell',
    powershell: 'powershell',
    bat: 'bat',
    cmd: 'bat',
    graphql: 'graphql',
    gql: 'graphql',
    dockerfile: 'dockerfile',
    makefile: 'shell',
    ini: 'ini',
    conf: 'ini',
    toml: 'ini',
    proto: 'proto3',
    vue: 'html',
    svelte: 'html',
    astro: 'html',
    zig: 'plaintext',
  };

  return languageIds[key] ?? 'plaintext';
};
